version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Run tests
          command: sbt test < /dev/null

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run:
          name: Build JAR
          command: sbt assembly < /dev/null
      - run: mkdir -p workspace
      - run: cp target/scala-2.12/hello.jar workspace/hello.jar
      - persist_to_workspace:
          root: workspace
          paths:
            - hello.jar
  deploy:
    docker:
      - image: artsy/hokusai:0.4.6
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: cp /tmp/workspace/hello.jar .
workflows:
  version: 2
  default:
    jobs:
      - build
      - deploy:
          requires:
            - build
